- import { ReactQueryProvider } from '@/components/providers'
- import { Sidebar } from '@/components/sidebar'
- import { Topbar } from '@/components/topbar'
- import { PageMotion } from '@/components/ui'
+ import { ReactQueryProvider } from '../components/providers'
+ import { Sidebar } from '../components/sidebar'
+ import { Topbar } from '../components/topbar'
+ import { PageMotion } from '../components/ui'
